'use strict';
const SCENARIOS = [
  {
    topic: 'PHISHING', title: 'Month-end has entered the chat.', intro: 'It’s 16:42. The client’s finance team is closing the month, and this lands in your inbox. What’s your best move?', kind: 'email', app: 'Inbox', sender: 'ERP Support Desk', address: 'support@ubuntu-erp-help.example', subject: 'Action required: your ERP access expires in 20 minutes', body: 'Hi consultant,\n\nYour session licence will be suspended before today’s close. Validate your Microsoft account now to keep posting journals.\n\nWe’ve made this quick. No ticket required.', action: 'Keep my access', destination: 'https://ubuntu-erp-login.example/validate',
    clues: [{label:'Sender',text:'A support-sounding display name is easy to fake. This is not the support address in your company directory.'},{label:'Destination',text:'The button leads to ubuntu-erp-login.example, not your known ERP portal. HTTPS alone does not establish trust.'}],
    options: ['Validate now — month-end cannot wait.', 'Open the ERP from my saved bookmark and contact the known support desk.', 'Reply to this email asking if it is genuine.'], correct:1,
    verdict:'Phishing: urgency is doing the heavy lifting.', explanation:'The unfamiliar sender, new login domain and suspension threat all call for independent verification. Open your usual portal and use the support details already in your directory. Replying to the sender lets the same person reassure you.', takeaway:'A deadline is a reason to verify, not a reason to skip verification.'
  },
  {
    topic:'TEAMS INVITATIONS',title:'A real meeting, for a change.',intro:'Yesterday, your project lead confirmed a 10:00 UAT call through your usual project channel. You open Teams yourself and see the matching calendar entry. What now?',kind:'meeting',app:'Team calendar',sender:'Naledi · Project lead',address:'Internal colleague · expected organiser',subject:'Karoo Retail | UAT sign-off',body:'Today, 10:00–10:30\n\nAgenda: review test evidence, agree open actions, confirm next steps.\n\nSame project team. No new app installation or unusual permission request.',action:'Join meeting',destination:'Join inside your already-open Teams app',
    clues:[{label:'Context',text:'The organiser, time and agenda match the call arranged independently in your usual channel.'},{label:'Join route',text:'You opened the known Teams app yourself. The invitation is not asking you to install a helper or sign in on a new website.'}],
    options:['Report every Teams invitation as phishing.','Install a “meeting compatibility checker” first, just in case.','Join from the known Teams app; stop if an unexpected sign-in or permission request appears.'],correct:2,
    verdict:'Reasonable to proceed through the verified route.',explanation:'Security is about context as well as warning signs. This meeting matches an independently arranged call and is in the app you opened yourself. Keep watching for changes: a familiar organiser or service alone does not make every request safe.',takeaway:'Expected context + a known route = a sensible next step.'
  },
  {
    topic:'QR CODES',title:'Free coffee. Expensive login?',intro:'At a client workshop in Sandton, a fresh sticker is sitting over the original Wi-Fi card. It promises a coffee voucher if you sign in with your work account.',kind:'qr',app:'Workshop notice',sender:'Welcome, consultants!',address:'Sticker over the venue’s original Wi-Fi instructions',subject:'Connect. Caffeinate. Claim.',body:'Scan for guest Wi-Fi + a free flat white.\n\nMicrosoft sign-in required to verify your voucher.',action:'Decorative QR — not scannable',destination:'Phone preview: https://guest-perks-login.example/microsoft',
    clues:[{label:'Physical clue',text:'The new sticker covers the original instructions. Ask the host which connection details are correct.'},{label:'Preview',text:'A coffee voucher requesting a work login on guest-perks-login.example is a mismatch. A QR code can conceal the same risky destination as an email link.'}],
    options:['Ask the workshop host for the official Wi-Fi details; avoid the voucher login.','Use my phone instead of my laptop — then it is safe.','Sign in, but only after checking for the padlock.'],correct:0,
    verdict:'Treat the QR destination like any other untrusted link.',explanation:'A QR code is a shortcut to content, not proof of trust. A different device or a padlock does not make the work-login request appropriate. Get the venue details from the host, and report the suspicious sticker.',takeaway:'Before you scan: check the source, preview the destination, question the request.'
  },
  {
    topic:'BANK DETAIL FRAUD',title:'Same supplier. Different bank.',intro:'You are helping with the payment run. An existing supplier emails from their usual address, in the real invoice thread. The message asks you to change their banking details today.',kind:'invoice',app:'Accounts payable',sender:'Thabo · Mzansi Parts',address:'accounts@mzansi-parts.example · known supplier address',subject:'RE: Invoice MP-2048 | banking update',body:'Please update our beneficiary before today’s payment run. Our old account is under audit.\n\nInvoice: MP-2048\nAmount: R 184 750,00\nBanking details: revised in attached letter\n\nUse the new phone number on the letter if you need to confirm.',action:'Bank-update-letter.pdf · mock attachment',destination:'Payment batch closes at 15:00',
    clues:[{label:'Familiar thread',text:'Attackers can take over a real mailbox. The correct address and invoice history do not validate a bank-account change.'},{label:'Callback trap',text:'The new number comes from the same unverified request. Use a trusted number already held in your supplier records.'}],
    options:['Update the beneficiary; the email address matches.','Hold the change, call the supplier on the existing trusted number and follow the approved verification and sign-off process.','Make a R 1 test payment to prove the account belongs to them.'],correct:1,
    verdict:'Verify the change outside the email thread.',explanation:'A compromised mailbox can send convincing requests in genuine conversations. Confirm bank changes using existing trusted contact details and your finance approval process. A successful test payment shows an account can receive money; it does not prove ownership.',takeaway:'When the bank details change, the verification channel should change too.'
  },
  {
    topic:'MFA PROMPTS',title:'Your phone wants a yes. Again.',intro:'You are eating lunch and haven’t tried to sign in. Your authenticator shows three approval prompts. Then a caller claiming to be IT asks you to approve one to “stop the alerts”.',kind:'phone',app:'Authenticator',sender:'Sign-in request',address:'You did not initiate this sign-in',subject:'Approve sign-in?',body:'Application: Work account\nApproximate location: unfamiliar\nRequest: 3 of 3\n\nCaller: “We’re doing a reset. Just approve the next one.”',action:'Approve / Deny · mock controls',destination:'Unexpected sign-in attempt',
    clues:[{label:'Timing',text:'You did not start a sign-in. That matters more than the approximate location, which can be inaccurate.'},{label:'Caller',text:'A caller telling you to approve an unexpected prompt is not independent confirmation. Contact IT through your established channel.'}],
    options:['Approve once so the notifications stop.','Read the caller the one-time code instead.','Deny, report immediately through the known IT/security channel and follow the account-protection instructions.'],correct:2,
    verdict:'Deny the request you did not start.',explanation:'Repeated prompts can pressure you into approving someone else’s sign-in. Never share authentication codes or approve an unexpected request on a caller’s instructions. Contact your known IT/security team promptly so they can investigate and secure the account.',takeaway:'MFA is a decision, not a reflex.'
  },
  {
    topic:'AI & CLIENT DATA',title:'Let AI do the boring bit?',intro:'You want AI to explain reconciliation differences. The client workbook contains names, bank accounts, salaries and invoice amounts. Your personal AI account is handy. What’s the safest useful approach?',kind:'ai',app:'Reconciliation workspace',sender:'Client month-end workbook',address:'Confidential · finance working papers',subject:'Recon_October.xlsx',body:'Tabs: payroll, supplier bank accounts, GL detail\n\nDraft prompt: “Find the differences and summarise what I should tell the CFO.”\n\nTool: personal AI account · client-data approval not confirmed',action:'Upload workbook · mock control',destination:'No files are uploaded in this quiz',
    clues:[{label:'Data',text:'Removing the client’s name alone leaves bank details, personal data and commercially sensitive figures. Hidden tabs and metadata can also expose information.'},{label:'Approval',text:'A paid or familiar tool is not automatically approved for this client’s data. Check the organisation’s policy and the client’s authorised use before sharing.'}],
    options:['Use synthetic examples now; use real data only in an approved environment with authorisation and the minimum necessary data.', 'Delete the client name from the filename, then upload the workbook.','Upload it to my paid personal account; paid accounts are always safe for client data.'],correct:0,
    verdict:'Useful AI starts with an approved data boundary.',explanation:'You can explore the reconciliation method using made-up data without disclosing the workbook. For real client information, establish authorisation, approved tooling and data-handling controls first. Minimise the data and review the output; simply removing names or paying for a tool is not enough.',takeaway:'If you cannot confirm permission, use synthetic data instead.'
  },
  {
    topic:'ERP NOTIFICATIONS',title:'The export you actually asked for.',intro:'You requested a trial-balance export in the client’s ERP five minutes ago. The expected notification arrives. You leave the email and open your saved ERP bookmark.',kind:'portal',app:'Known ERP portal',sender:'Your export queue',address:'Opened from your established bookmark',subject:'Trial balance export is ready',body:'Requested by: you\nCompany: Karoo Retail\nPeriod: September\nStatus: completed\n\nThe export appears in the authenticated portal’s own job history, with the scope you requested.',action:'Download from the known portal',destination:'No macro, extension or extra sign-in is requested',
    clues:[{label:'Request match',text:'The timing, company and period match the export you initiated. You also checked the portal’s job history directly.'},{label:'Data handling',text:'A legitimate download can still contain confidential data. Keep it in an approved work location and limit sharing.'}],
    options:['Forward it to my personal email to work on later.','Download through the verified portal and keep it in the approved work location.','Report it automatically because financial files are always phishing.'],correct:1,
    verdict:'Proceed, and keep the financial data protected.',explanation:'This is consistent with the job you started, verified in the portal you opened independently. Use the approved storage and sharing arrangements. A routine task is not automatically malicious, and a legitimate file is not automatically suitable for personal storage.',takeaway:'Verify the source, then protect the contents.'
  },
  {
    topic:'WHEN SOMETHING GOES WRONG',title:'Oops is not the end of the story.',intro:'You clicked a fake file-share link and entered your work password. The next page looked wrong, so you closed it. No download appeared. What should you do first?',kind:'incident',app:'File-share sign-in',sender:'Something felt off',address:'Password entered on an unfamiliar website',subject:'“Session expired. Try again.”',body:'You entered your password.\nThe page refreshed.\nNo file downloaded.\n\nYou still have the original message and approximate time of the click.',action:'Pause. Report. Recover.',destination:'Closing a tab does not undo what was submitted',
    clues:[{label:'Exposure',text:'The password may already have been captured. A missing download does not mean no harm occurred.'},{label:'Next step',text:'Prompt reporting gives the security team time to reset access, revoke sessions and investigate. Keep the original message and time available.'}],
    options:['Wait until I see an unusual transaction.','Delete the message so nobody else clicks it, and carry on.','Report immediately via the known security channel; reset my password through the official route and follow their containment steps.'],correct:2,
    verdict:'Fast reporting helps the whole team.',explanation:'Tell IT/security promptly what happened, including the link, timing and credentials entered. Use the official password-reset route and follow their guidance on sessions and account containment. Do not wait for visible damage or delete the evidence. If payments may be affected, alert finance through the approved process too.',takeaway:'Report early. No shame, no delay.'
  }
];
